# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: adib070/ad
        ports:
        - containerPort: 9555
        resources:
          requests:
            cpu: 200m
            memory: 280Mi
          limits:
            cpu: 300m
            memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ad
spec:
  type: ClusterIP
  selector:
    app: ad
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
